#!/usr/bin/env bash

printf "\n\tMaking 'data' dir.\n"
mkdir data && cd data
cd data
printf "\n\tDownloading 'raspberrypi.stackexchange.com.7z'.\n\n"
wget https://archive.org/download/stackexchange/raspberrypi.stackexchange.com.7z

printf "\n\n\tMaking 'stackoverflow' dir.\n"
mkdir stackoverflow && cd stackoverflow

printf "\n\tExtracting 'raspberrypi.stackexchange.com.7z'.\n\n"
7z e ../*.7z

printf "\n\n\tDONE\n"
